import type { WarehousePosition } from './types';

export const initialWarehouseData: WarehousePosition[] = [
  {
    id: 'rack-a1',
    code: 'R-A-01-1',
    type: 'RACK',
    position: [-10, 2.5, -5],
    rotation: [0, 0, 0],
    dimensions: [4, 5, 1],
    occupancyPercentage: 85,
    status: 'NORMAL',
    items: [
      { sku: 'SKU-001', description: 'Heavy Machinery Parts', quantity: 50 },
      { sku: 'SKU-002', description: 'Electronic Components', quantity: 200 },
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'rack-a2',
    code: 'R-A-02-1',
    type: 'RACK',
    position: [-10, 2.5, 0],
    rotation: [0, 0, 0],
    dimensions: [4, 5, 1],
    occupancyPercentage: 95,
    status: 'ALERT',
    items: [
      { sku: 'SKU-003', description: 'Finished Goods - A', quantity: 150 },
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'rack-a3',
    code: 'R-A-03-1',
    type: 'RACK',
    position: [-10, 2.5, 5],
    rotation: [0, 0, 0],
    dimensions: [4, 5, 1],
    occupancyPercentage: 0,
    status: 'EMPTY',
    items: [],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'floor-b1',
    code: 'F-B-01',
    type: 'FLOOR_BLOCK',
    position: [0, 0.1, -5],
    rotation: [0, 0, 0],
    dimensions: [5, 0.2, 5],
    occupancyPercentage: 50,
    status: 'NORMAL',
    items: [
      { sku: 'SKU-004', description: 'Palletized Raw Materials', quantity: 5, lpn: 'LPN-B1-001' },
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'floor-b2',
    code: 'F-B-02',
    type: 'FLOOR_BLOCK',
    position: [0, 0.1, 5],
    rotation: [0, 0, 0],
    dimensions: [5, 0.2, 5],
    occupancyPercentage: 100,
    status: 'BLOCKED',
    items: [
      { sku: 'SKU-005', description: 'Goods for QC', quantity: 10, lpn: 'LPN-B2-001' },
    ],
    lastUpdated: new Date().toISOString(),
  },
    {
    id: 'rack-c1',
    code: 'R-C-01-1',
    type: 'RACK',
    position: [10, 2.5, -5],
    rotation: [0, 0, 0],
    dimensions: [4, 5, 1],
    occupancyPercentage: 110,
    status: 'ALERT',
    items: [
      { sku: 'SKU-006', description: 'Overstocked items', quantity: 250 },
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'rack-c2',
    code: 'R-C-02-1',
    type: 'RACK',
    position: [10, 2.5, 0],
    rotation: [0, 0, 0],
    dimensions: [4, 5, 1],
    occupancyPercentage: 20,
    status: 'NORMAL',
    items: [
      { sku: 'SKU-007', description: 'Fast-moving consumer goods', quantity: 30 },
    ],
    lastUpdated: new Date().toISOString(),
  },
];
